// Command apicontract writes the API's error vocabulary to a file.
//
// The interface has to know every machine code the server can answer with, so
// that each one has a message in each language. It used to learn that by
// walking the Go sources with a regular expression, which was both a
// dependency on another language's layout and wrong: a code written anywhere
// but the expected call shape was invisible, and one shipped with no message
// in any language while the check reported success.
//
// This publishes the same knowledge as data. The catalog it reads cannot be
// incomplete — a code that is not declared cannot be sent, because
// httpx.Error takes a declared type and not a string — so the file is exact by
// construction rather than by pattern matching.
//
// It is generated, committed and checked by a test:
//
//	make api-contract
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	// Imported for their side effect: declaring codes. The catalog is
	// populated by package initialisation, so every package that answers with
	// codes has to be linked in here.
	_ "github.com/devrdn/db-contest/backend/internal/api"
	"github.com/devrdn/db-contest/backend/internal/platform/httpx"
)

// contractFile is where the published contract lives, relative to the
// repository root.
//
// Under docs/ rather than inside either application: it is the boundary
// between them, and it belongs to neither. If the two ever move to separate
// repositories, this file is what the backend publishes and the interface
// consumes — the only thing that has to change is where the consumer fetches
// it from.
const contractFile = "docs/api/error-codes.json"

// contractPath resolves contractFile against the repository root.
//
// Found by walking up to the directory holding go.mod rather than trusting the
// working directory: `go run ./cmd/apicontract` starts in the module root and
// `go test` starts in the package's own directory, and a relative path cannot
// be right for both.
func contractPath() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("locate the working directory: %w", err)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return filepath.Join(filepath.Dir(dir), contractFile), nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above the working directory")
		}
		dir = parent
	}
}

// document is the published shape. A wrapper object rather than a bare array
// so the file can gain a field later without every consumer breaking.
type document struct {
	// About says what the file is, to whoever opens it without context.
	About string           `json:"about"`
	Codes []httpx.CodeInfo `json:"codes"`
}

func contract() ([]byte, error) {
	out, err := json.MarshalIndent(document{
		About: "Machine codes this API answers with in error.code. Generated by cmd/apicontract; " +
			"run `make api-contract` after changing them. The message beside the code on the wire " +
			"is for developers; clients translate the code themselves.",
		Codes: httpx.Catalog(),
	}, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode the contract: %w", err)
	}
	return append(out, '\n'), nil
}

func main() {
	out, err := contract()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	path, err := contractPath()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	// Narrow modes on purpose: git records neither directory permissions nor
	// anything but the executable bit, so what is committed is unaffected and
	// there is nothing to gain by asking for more on the machine that
	// generates the file.
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		fmt.Fprintf(os.Stderr, "create %s: %v\n", filepath.Dir(path), err)
		os.Exit(1)
	}
	if err := os.WriteFile(path, out, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", path)
}
