// Command apicontract writes the API's error codes to a file the interface
// checks its translations against. The catalog it reads is complete by
// construction: httpx.Error accepts only declared codes.
//
// It is generated, committed and checked by a test:
//
//	make api-contract
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	// Imported to declare codes at init; every package with codes must be
	// linked in.
	_ "github.com/devrdn/db-contest/backend/internal/api"
	"github.com/devrdn/db-contest/backend/internal/platform/httpx"
)

// contractFile is relative to the repository root, under docs/ because it
// belongs to neither application.
const contractFile = "docs/api/error-codes.json"

// contractPath resolves contractFile by walking up to go.mod, since `go run`
// and `go test` start in different directories.
func contractPath() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("locate the working directory: %w", err)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return filepath.Join(filepath.Dir(dir), contractFile), nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above the working directory")
		}
		dir = parent
	}
}

// document is an object rather than a bare array, so it can gain fields.
type document struct {
	About string           `json:"about"`
	Codes []httpx.CodeInfo `json:"codes"`
}

func contract() ([]byte, error) {
	out, err := json.MarshalIndent(document{
		About: "Machine codes this API answers with in error.code. Generated by cmd/apicontract; " +
			"run `make api-contract` after changing them. The message beside the code on the wire " +
			"is for developers; clients translate the code themselves.",
		Codes: httpx.Catalog(),
	}, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode the contract: %w", err)
	}
	return append(out, '\n'), nil
}

func main() {
	out, err := contract()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	path, err := contractPath()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	// Narrow modes: git records only the executable bit anyway.
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		fmt.Fprintf(os.Stderr, "create %s: %v\n", filepath.Dir(path), err)
		os.Exit(1)
	}
	if err := os.WriteFile(path, out, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", path)
}
