// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: queryrunner/v1/queryrunner.proto

// The contract between the Core API and the Query Runner.
//
// The Query Runner is the one component that is a separate service (section
// 2.3), and this file is the whole of what the two say to each other. Two
// reasons for the split, and the second is the one worth remembering:
//
//   - The runner links PostgreSQL's own parser through cgo, to check a query
//     before running it. That is C code reading text an adversary chooses, and
//     a crash in it takes down the process rather than raising an error a
//     recover can catch. In one process with the Core API, a crafted query
//     would be a repeatable way to end sign-in, the timer and the submission
//     of answers — the very things section 4 insists must survive everything.
//   - Only this service holds the game cluster's credentials. In one process,
//     a fault anywhere in the API would be within reach of every participant's
//     database.
//
// Scaling is *not* among the reasons. On one on-premise machine serving a few
// hundred participants, nobody is going to replicate this.

package queryrunnerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryRunner_Run_FullMethodName = "/dbcontest.queryrunner.v1.QueryRunner/Run"
)

// QueryRunnerClient is the client API for QueryRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryRunnerClient interface {
	// Run checks one participant's query against the contest's policy and, if it
	// passes, executes it in that participant's own database.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type queryRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryRunnerClient(cc grpc.ClientConnInterface) QueryRunnerClient {
	return &queryRunnerClient{cc}
}

func (c *queryRunnerClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, QueryRunner_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryRunnerServer is the server API for QueryRunner service.
// All implementations must embed UnimplementedQueryRunnerServer
// for forward compatibility.
type QueryRunnerServer interface {
	// Run checks one participant's query against the contest's policy and, if it
	// passes, executes it in that participant's own database.
	Run(context.Context, *RunRequest) (*RunResponse, error)
	mustEmbedUnimplementedQueryRunnerServer()
}

// UnimplementedQueryRunnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryRunnerServer struct{}

func (UnimplementedQueryRunnerServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedQueryRunnerServer) mustEmbedUnimplementedQueryRunnerServer() {}
func (UnimplementedQueryRunnerServer) testEmbeddedByValue()                     {}

// UnsafeQueryRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryRunnerServer will
// result in compilation errors.
type UnsafeQueryRunnerServer interface {
	mustEmbedUnimplementedQueryRunnerServer()
}

func RegisterQueryRunnerServer(s grpc.ServiceRegistrar, srv QueryRunnerServer) {
	// If the following call pancis, it indicates UnimplementedQueryRunnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryRunner_ServiceDesc, srv)
}

func _QueryRunner_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryRunnerServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryRunner_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryRunnerServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryRunner_ServiceDesc is the grpc.ServiceDesc for QueryRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbcontest.queryrunner.v1.QueryRunner",
	HandlerType: (*QueryRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _QueryRunner_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queryrunner/v1/queryrunner.proto",
}
