// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: queryrunner/v1/queryrunner.proto

// The contract between the Core API and the Query Runner.
//
// The Query Runner is the one component that is a separate service (section
// 2.3), and this file is the whole of what the two say to each other. Two
// reasons for the split, and the second is the one worth remembering:
//
//   - The runner links PostgreSQL's own parser through cgo, to check a query
//     before running it. That is C code reading text an adversary chooses, and
//     a crash in it takes down the process rather than raising an error a
//     recover can catch. In one process with the Core API, a crafted query
//     would be a repeatable way to end sign-in, the timer and the submission
//     of answers — the very things section 4 insists must survive everything.
//   - Only this service holds the game cluster's credentials. In one process,
//     a fault anywhere in the API would be within reach of every participant's
//     database.
//
// Scaling is *not* among the reasons. On one on-premise machine serving a few
// hundred participants, nobody is going to replicate this.

package queryrunnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Failure_Kind int32

const (
	Failure_KIND_UNSPECIFIED Failure_Kind = 0
	// The validator would not allow it. `code` and `subject` carry which rule
	// and which construct, so the Core API can say it in the participant's
	// own language rather than forwarding an English sentence.
	Failure_KIND_REFUSED Failure_Kind = 1
	// Admission control declined: the instance is full, or this participant
	// already has a query in flight.
	Failure_KIND_BUSY            Failure_Kind = 2
	Failure_KIND_ALREADY_RUNNING Failure_Kind = 3
	// The runner's own deadline fired and the query was cancelled.
	Failure_KIND_TIMEOUT Failure_Kind = 4
	// The database refused it — a missing table, a type error, a privilege.
	Failure_KIND_DATABASE_ERROR Failure_Kind = 5
	// The caller stopped waiting. Separate from a timeout because only one of
	// the two is about load, and a report of "how often did queries run out of
	// time" is read as though it were.
	Failure_KIND_CANCELLED Failure_Kind = 6
	// The participant is asking faster than the contest allows. Separate from
	// BUSY: one is about this person's rate, the other about everyone's load,
	// and the sentence a participant should read differs.
	Failure_KIND_RATE_LIMITED Failure_Kind = 7
	// The write was refused because the participant's database is at its size
	// limit.
	Failure_KIND_DISK_FULL Failure_Kind = 8
)

// Enum value maps for Failure_Kind.
var (
	Failure_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_REFUSED",
		2: "KIND_BUSY",
		3: "KIND_ALREADY_RUNNING",
		4: "KIND_TIMEOUT",
		5: "KIND_DATABASE_ERROR",
		6: "KIND_CANCELLED",
		7: "KIND_RATE_LIMITED",
		8: "KIND_DISK_FULL",
	}
	Failure_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":     0,
		"KIND_REFUSED":         1,
		"KIND_BUSY":            2,
		"KIND_ALREADY_RUNNING": 3,
		"KIND_TIMEOUT":         4,
		"KIND_DATABASE_ERROR":  5,
		"KIND_CANCELLED":       6,
		"KIND_RATE_LIMITED":    7,
		"KIND_DISK_FULL":       8,
	}
)

func (x Failure_Kind) Enum() *Failure_Kind {
	p := new(Failure_Kind)
	*p = x
	return p
}

func (x Failure_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Failure_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_queryrunner_v1_queryrunner_proto_enumTypes[0].Descriptor()
}

func (Failure_Kind) Type() protoreflect.EnumType {
	return &file_queryrunner_v1_queryrunner_proto_enumTypes[0]
}

func (x Failure_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Failure_Kind.Descriptor instead.
func (Failure_Kind) EnumDescriptor() ([]byte, []int) {
	return file_queryrunner_v1_queryrunner_proto_rawDescGZIP(), []int{6, 0}
}

// Policy is the contest's answer to "what may a participant's SQL do".
//
// Sent with every request rather than held by the runner, because it belongs
// to the contest and the runner is stateless. It mirrors sqlpolicy.Policy;
// the fields are named the same so that a mismatch reads as one.
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "read_only" or "read_write". Deliberately not an enum: the value is a
	// domain constant, and an enum here would be a second place to add one.
	Mode            *string  `protobuf:"bytes,1,opt,name=mode" json:"mode,omitempty"`
	WritableTables  []string `protobuf:"bytes,2,rep,name=writable_tables,json=writableTables" json:"writable_tables,omitempty"`
	AllowCreateView *bool    `protobuf:"varint,3,opt,name=allow_create_view,json=allowCreateView" json:"allow_create_view,omitempty"`
	AllowOwnTables  *bool    `protobuf:"varint,4,opt,name=allow_own_tables,json=allowOwnTables" json:"allow_own_tables,omitempty"`
	AllowTempTables *bool    `protobuf:"varint,5,opt,name=allow_temp_tables,json=allowTempTables" json:"allow_temp_tables,omitempty"`
	AllowCatalog    *bool    `protobuf:"varint,6,opt,name=allow_catalog,json=allowCatalog" json:"allow_catalog,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_queryrunner_v1_queryrunner_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

func (x *Policy) GetWritableTables() []string {
	if x != nil {
		return x.WritableTables
	}
	return nil
}

func (x *Policy) GetAllowCreateView() bool {
	if x != nil && x.AllowCreateView != nil {
		return *x.AllowCreateView
	}
	return false
}

func (x *Policy) GetAllowOwnTables() bool {
	if x != nil && x.AllowOwnTables != nil {
		return *x.AllowOwnTables
	}
	return false
}

func (x *Policy) GetAllowTempTables() bool {
	if x != nil && x.AllowTempTables != nil {
		return *x.AllowTempTables
	}
	return false
}

func (x *Policy) GetAllowCatalog() bool {
	if x != nil && x.AllowCatalog != nil {
		return *x.AllowCatalog
	}
	return false
}

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The registration asking, which is what "one query at a time" counts: the
	// same person in two contests is two participants.
	Registration *string `protobuf:"bytes,1,opt,name=registration" json:"registration,omitempty"`
	// The participant's own game database. It comes from game_instances on the
	// Core API's side and never from the client — section 5, point 1.
	Database      *string `protobuf:"bytes,2,opt,name=database" json:"database,omitempty"`
	Sql           *string `protobuf:"bytes,3,opt,name=sql" json:"sql,omitempty"`
	Policy        *Policy `protobuf:"bytes,4,opt,name=policy" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_queryrunner_v1_queryrunner_proto_rawDescGZIP(), []int{1}
}

func (x *RunRequest) GetRegistration() string {
	if x != nil && x.Registration != nil {
		return *x.Registration
	}
	return ""
}

func (x *RunRequest) GetDatabase() string {
	if x != nil && x.Database != nil {
		return *x.Database
	}
	return ""
}

func (x *RunRequest) GetSql() string {
	if x != nil && x.Sql != nil {
		return *x.Sql
	}
	return ""
}

func (x *RunRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type RunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one. A refusal, a timeout and a full instance are ordinary
	// outcomes of asking, not faults of the transport, so they travel in the
	// response rather than as a gRPC error status. A gRPC error from this call
	// means the runner could not be reached or could not answer at all.
	//
	// Types that are valid to be assigned to Outcome:
	//
	//	*RunResponse_Result
	//	*RunResponse_Failure
	Outcome       isRunResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_queryrunner_v1_queryrunner_proto_rawDescGZIP(), []int{2}
}

func (x *RunResponse) GetOutcome() isRunResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *RunResponse) GetResult() *Result {
	if x != nil {
		if x, ok := x.Outcome.(*RunResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *RunResponse) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*RunResponse_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isRunResponse_Outcome interface {
	isRunResponse_Outcome()
}

type RunResponse_Result struct {
	Result *Result `protobuf:"bytes,1,opt,name=result,oneof"`
}

type RunResponse_Failure struct {
	Failure *Failure `protobuf:"bytes,2,opt,name=failure,oneof"`
}

func (*RunResponse_Result) isRunResponse_Outcome() {}

func (*RunResponse_Failure) isRunResponse_Outcome() {}

type Result struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Columns []string               `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
	Rows    []*Row                 `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	// The answer is longer than what is here — by rows, by bytes, or both. A
	// flag rather than a silent cut: a participant reading nine hundred rows of
	// a nine thousand row answer and not being told has a wrong answer, not a
	// short one.
	Truncated     *bool `protobuf:"varint,3,opt,name=truncated" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_queryrunner_v1_queryrunner_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Result) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *Result) GetTruncated() bool {
	if x != nil && x.Truncated != nil {
		return *x.Truncated
	}
	return false
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_queryrunner_v1_queryrunner_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

// Cell is one value, rendered.
//
// Text rather than a typed union, because the only consumer is a console that
// displays it. `is_null` is separate so that NULL and the empty string stay
// different, which in SQL they very much are.
type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsNull        *bool                  `protobuf:"varint,1,opt,name=is_null,json=isNull" json:"is_null,omitempty"`
	Text          *string                `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_queryrunner_v1_queryrunner_proto_rawDescGZIP(), []int{5}
}

func (x *Cell) GetIsNull() bool {
	if x != nil && x.IsNull != nil {
		return *x.IsNull
	}
	return false
}

func (x *Cell) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type Failure struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Kind    *Failure_Kind          `protobuf:"varint,1,opt,name=kind,enum=dbcontest.queryrunner.v1.Failure_Kind" json:"kind,omitempty"`
	Code    *string                `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Subject *string                `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	// For the journal and the technical log. Not for the participant: what they
	// are shown is chosen from `kind` and `code`.
	Message       *string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_queryrunner_v1_queryrunner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_queryrunner_v1_queryrunner_proto_rawDescGZIP(), []int{6}
}

func (x *Failure) GetKind() Failure_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Failure_KIND_UNSPECIFIED
}

func (x *Failure) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *Failure) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *Failure) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_queryrunner_v1_queryrunner_proto protoreflect.FileDescriptor

const file_queryrunner_v1_queryrunner_proto_rawDesc = "" +
	"\n" +
	" queryrunner/v1/queryrunner.proto\x12\x18dbcontest.queryrunner.v1\"\xec\x01\n" +
	"\x06Policy\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12'\n" +
	"\x0fwritable_tables\x18\x02 \x03(\tR\x0ewritableTables\x12*\n" +
	"\x11allow_create_view\x18\x03 \x01(\bR\x0fallowCreateView\x12(\n" +
	"\x10allow_own_tables\x18\x04 \x01(\bR\x0eallowOwnTables\x12*\n" +
	"\x11allow_temp_tables\x18\x05 \x01(\bR\x0fallowTempTables\x12#\n" +
	"\rallow_catalog\x18\x06 \x01(\bR\fallowCatalog\"\x98\x01\n" +
	"\n" +
	"RunRequest\x12\"\n" +
	"\fregistration\x18\x01 \x01(\tR\fregistration\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x10\n" +
	"\x03sql\x18\x03 \x01(\tR\x03sql\x128\n" +
	"\x06policy\x18\x04 \x01(\v2 .dbcontest.queryrunner.v1.PolicyR\x06policy\"\x93\x01\n" +
	"\vRunResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\v2 .dbcontest.queryrunner.v1.ResultH\x00R\x06result\x12=\n" +
	"\afailure\x18\x02 \x01(\v2!.dbcontest.queryrunner.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"s\n" +
	"\x06Result\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x121\n" +
	"\x04rows\x18\x02 \x03(\v2\x1d.dbcontest.queryrunner.v1.RowR\x04rows\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\";\n" +
	"\x03Row\x124\n" +
	"\x05cells\x18\x01 \x03(\v2\x1e.dbcontest.queryrunner.v1.CellR\x05cells\"3\n" +
	"\x04Cell\x12\x17\n" +
	"\ais_null\x18\x01 \x01(\bR\x06isNull\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xd1\x02\n" +
	"\aFailure\x12:\n" +
	"\x04kind\x18\x01 \x01(\x0e2&.dbcontest.queryrunner.v1.Failure.KindR\x04kind\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xc1\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fKIND_REFUSED\x10\x01\x12\r\n" +
	"\tKIND_BUSY\x10\x02\x12\x18\n" +
	"\x14KIND_ALREADY_RUNNING\x10\x03\x12\x10\n" +
	"\fKIND_TIMEOUT\x10\x04\x12\x17\n" +
	"\x13KIND_DATABASE_ERROR\x10\x05\x12\x12\n" +
	"\x0eKIND_CANCELLED\x10\x06\x12\x15\n" +
	"\x11KIND_RATE_LIMITED\x10\a\x12\x12\n" +
	"\x0eKIND_DISK_FULL\x10\b2a\n" +
	"\vQueryRunner\x12R\n" +
	"\x03Run\x12$.dbcontest.queryrunner.v1.RunRequest\x1a%.dbcontest.queryrunner.v1.RunResponseBAZ?github.com/devrdn/db-contest/backend/internal/rpc/queryrunnerv1b\beditionsp\xe8\a"

var (
	file_queryrunner_v1_queryrunner_proto_rawDescOnce sync.Once
	file_queryrunner_v1_queryrunner_proto_rawDescData []byte
)

func file_queryrunner_v1_queryrunner_proto_rawDescGZIP() []byte {
	file_queryrunner_v1_queryrunner_proto_rawDescOnce.Do(func() {
		file_queryrunner_v1_queryrunner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queryrunner_v1_queryrunner_proto_rawDesc), len(file_queryrunner_v1_queryrunner_proto_rawDesc)))
	})
	return file_queryrunner_v1_queryrunner_proto_rawDescData
}

var file_queryrunner_v1_queryrunner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_queryrunner_v1_queryrunner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_queryrunner_v1_queryrunner_proto_goTypes = []any{
	(Failure_Kind)(0),   // 0: dbcontest.queryrunner.v1.Failure.Kind
	(*Policy)(nil),      // 1: dbcontest.queryrunner.v1.Policy
	(*RunRequest)(nil),  // 2: dbcontest.queryrunner.v1.RunRequest
	(*RunResponse)(nil), // 3: dbcontest.queryrunner.v1.RunResponse
	(*Result)(nil),      // 4: dbcontest.queryrunner.v1.Result
	(*Row)(nil),         // 5: dbcontest.queryrunner.v1.Row
	(*Cell)(nil),        // 6: dbcontest.queryrunner.v1.Cell
	(*Failure)(nil),     // 7: dbcontest.queryrunner.v1.Failure
}
var file_queryrunner_v1_queryrunner_proto_depIdxs = []int32{
	1, // 0: dbcontest.queryrunner.v1.RunRequest.policy:type_name -> dbcontest.queryrunner.v1.Policy
	4, // 1: dbcontest.queryrunner.v1.RunResponse.result:type_name -> dbcontest.queryrunner.v1.Result
	7, // 2: dbcontest.queryrunner.v1.RunResponse.failure:type_name -> dbcontest.queryrunner.v1.Failure
	5, // 3: dbcontest.queryrunner.v1.Result.rows:type_name -> dbcontest.queryrunner.v1.Row
	6, // 4: dbcontest.queryrunner.v1.Row.cells:type_name -> dbcontest.queryrunner.v1.Cell
	0, // 5: dbcontest.queryrunner.v1.Failure.kind:type_name -> dbcontest.queryrunner.v1.Failure.Kind
	2, // 6: dbcontest.queryrunner.v1.QueryRunner.Run:input_type -> dbcontest.queryrunner.v1.RunRequest
	3, // 7: dbcontest.queryrunner.v1.QueryRunner.Run:output_type -> dbcontest.queryrunner.v1.RunResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_queryrunner_v1_queryrunner_proto_init() }
func file_queryrunner_v1_queryrunner_proto_init() {
	if File_queryrunner_v1_queryrunner_proto != nil {
		return
	}
	file_queryrunner_v1_queryrunner_proto_msgTypes[2].OneofWrappers = []any{
		(*RunResponse_Result)(nil),
		(*RunResponse_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queryrunner_v1_queryrunner_proto_rawDesc), len(file_queryrunner_v1_queryrunner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queryrunner_v1_queryrunner_proto_goTypes,
		DependencyIndexes: file_queryrunner_v1_queryrunner_proto_depIdxs,
		EnumInfos:         file_queryrunner_v1_queryrunner_proto_enumTypes,
		MessageInfos:      file_queryrunner_v1_queryrunner_proto_msgTypes,
	}.Build()
	File_queryrunner_v1_queryrunner_proto = out.File
	file_queryrunner_v1_queryrunner_proto_goTypes = nil
	file_queryrunner_v1_queryrunner_proto_depIdxs = nil
}
