package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/devrdn/db-contest/backend/internal/provisioning"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// The table builder's own per-table data (migration 27): the bookkeeping for
// a table's CSV file, mirroring gameuploads.go's own shape for a whole dump
// at the finer grain of one table. Apart from gametemplates.go and
// gameuploads.go in the same sense those two are apart from each other — one
// table, its own job, touching game_templates only to read the current
// definition (through provisioning.Games, never a query in this file).

const tableDataColumns = `id, contest_id, table_name, declared_bytes, received_bytes,
	coalesce(line_count, 0), coalesce(deleted_rows, '{}'), status, created_at, updated_at`

// tableDataCheckViolation is the SQLSTATE PostgreSQL uses for any CHECK
// constraint — migration 27's own bound on deleted_rows among them. Not
// named checkViolation: contests_test.go already declares that identifier in
// this package for its own tests.
const tableDataCheckViolation = "23514"

func scanTableData(row pgx.Row) (provisioning.TableData, error) {
	var d provisioning.TableData
	var status string
	err := row.Scan(&d.ID, &d.ContestID, &d.Table, &d.DeclaredBytes, &d.ReceivedBytes,
		&d.Lines, &d.DeletedRows, &status, &d.CreatedAt, &d.UpdatedAt)
	d.Status = provisioning.TableDataStatus(status)
	return d, err
}

// BeginTableData records a new table-data upload in 'receiving'. id is
// generated by the caller (provisioning.Games.BeginTableUpload) so the same
// id can name a reservation on disk before this row exists.
//
// "One unfinished upload per table" is migration 27's own partial index
// (game_table_data_one_receiving_idx), not a read here ahead of the INSERT —
// the same reasoning BeginUpload's own doc gives.
func (r *GameInstances) BeginTableData(
	ctx context.Context, id, contestID uuid.UUID, table string, declaredBytes int64,
) (provisioning.TableData, error) {
	data, err := scanTableData(r.querier(ctx).QueryRow(ctx, `
		INSERT INTO game_table_data (id, contest_id, table_name, declared_bytes)
		VALUES ($1, $2, $3, $4)
		RETURNING `+tableDataColumns, id, contestID, table, declaredBytes))
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == uniqueViolation {
			return provisioning.TableData{}, provisioning.ErrTableDataInProgress
		}
		return provisioning.TableData{}, fmt.Errorf("record the table upload: %w", err)
	}
	return data, nil
}

// TableDataByID reads one table-data row by id, or ErrTableDataNotFound.
func (r *GameInstances) TableDataByID(ctx context.Context, id uuid.UUID) (provisioning.TableData, error) {
	data, err := scanTableData(r.querier(ctx).QueryRow(ctx,
		`SELECT `+tableDataColumns+` FROM game_table_data WHERE id = $1`, id))
	if errors.Is(err, pgx.ErrNoRows) {
		return provisioning.TableData{}, provisioning.ErrTableDataNotFound
	}
	if err != nil {
		return provisioning.TableData{}, fmt.Errorf("read the table upload: %w", err)
	}
	return data, nil
}

// CurrentTableData reads a table's one 'receiving' upload, or
// ErrTableDataNotFound when it has none — game_table_data_one_receiving_idx
// is what guarantees there is never more than one row for this to find.
func (r *GameInstances) CurrentTableData(ctx context.Context, contestID uuid.UUID, table string) (provisioning.TableData, error) {
	data, err := scanTableData(r.querier(ctx).QueryRow(ctx,
		`SELECT `+tableDataColumns+` FROM game_table_data
		 WHERE contest_id = $1 AND lower(table_name) = lower($2) AND status = 'receiving'`, contestID, table))
	if errors.Is(err, pgx.ErrNoRows) {
		return provisioning.TableData{}, provisioning.ErrTableDataNotFound
	}
	if err != nil {
		return provisioning.TableData{}, fmt.Errorf("read the table's current upload: %w", err)
	}
	return data, nil
}

// ReadyTableData reads a table's one 'complete' file, or
// ErrTableDataNotFound when the table has none yet —
// game_table_data_one_complete_idx guarantees there is never more than one.
func (r *GameInstances) ReadyTableData(ctx context.Context, contestID uuid.UUID, table string) (provisioning.TableData, error) {
	data, err := scanTableData(r.querier(ctx).QueryRow(ctx,
		`SELECT `+tableDataColumns+` FROM game_table_data
		 WHERE contest_id = $1 AND lower(table_name) = lower($2) AND status = 'complete'`, contestID, table))
	if errors.Is(err, pgx.ErrNoRows) {
		return provisioning.TableData{}, provisioning.ErrTableDataNotFound
	}
	if err != nil {
		return provisioning.TableData{}, fmt.Errorf("read the table's current data: %w", err)
	}
	return data, nil
}

// UpdateTableDataReceived records how many bytes Store.Append actually
// wrote, the same job UpdateReceived does for a dump.
func (r *GameInstances) UpdateTableDataReceived(ctx context.Context, id uuid.UUID, receivedBytes int64) error {
	if _, err := r.querier(ctx).Exec(ctx,
		`UPDATE game_table_data SET received_bytes = $2, updated_at = now() WHERE id = $1`,
		id, receivedBytes); err != nil {
		return fmt.Errorf("record the table upload's progress: %w", err)
	}
	return nil
}

// CompleteTableData marks id 'complete' with what the validation pass
// measured, and retires previous (the file this one displaces, if any) —
// CompleteUpload's own shape, one table at a time instead of one whole game.
func (r *GameInstances) CompleteTableData(
	ctx context.Context, contestID uuid.UUID, table string, id uuid.UUID, receivedBytes, lines int64, previous *uuid.UUID,
) (provisioning.TableData, error) {
	// The displaced row is retired *before* this one is marked complete: for
	// one instant otherwise, both id and *previous would read 'complete' for
	// the same (contest, table), which is exactly what
	// game_table_data_one_complete_idx exists to forbid — an UPDATE that
	// tried the other order found that out the hard way (23505 on this very
	// statement, not on some unrelated later write).
	if previous != nil {
		if _, err := r.querier(ctx).Exec(ctx,
			`UPDATE game_table_data SET status = 'aborted', updated_at = now() WHERE id = $1`, *previous); err != nil {
			return provisioning.TableData{}, fmt.Errorf("retire the displaced table upload's row: %w", err)
		}
	}

	if _, err := r.querier(ctx).Exec(ctx, `
		UPDATE game_table_data
		SET status = 'complete', received_bytes = $2, line_count = $3, updated_at = now()
		WHERE id = $1 AND status = 'receiving'`, id, receivedBytes, lines); err != nil {
		return provisioning.TableData{}, fmt.Errorf("mark the table upload complete: %w", err)
	}

	return r.TableDataByID(ctx, id)
}

// CreateReadyTableData records a table's very first row: a file that starts
// life already 'complete', the bootstrap AppendTableRow's own doc explains.
func (r *GameInstances) CreateReadyTableData(
	ctx context.Context, id, contestID uuid.UUID, table string, bytes, lines int64,
) (provisioning.TableData, error) {
	data, err := scanTableData(r.querier(ctx).QueryRow(ctx, `
		INSERT INTO game_table_data (id, contest_id, table_name, declared_bytes, received_bytes, line_count, status)
		VALUES ($1, $2, $3, $4, $4, $5, 'complete')
		RETURNING `+tableDataColumns, id, contestID, table, bytes, lines))
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == uniqueViolation {
			return provisioning.TableData{}, provisioning.ErrTableDataInProgress
		}
		return provisioning.TableData{}, fmt.Errorf("record the table's first row: %w", err)
	}
	return data, nil
}

// MarkTableDataChanged records that this contest's built game no longer holds
// the data its tables do. A contest with no game row at all is not an error:
// the data is stored, the game will be written later, and the build that
// writes it loads everything there is.
//
// clock_timestamp(), not now(): now() is transaction-start time, so a mark
// whose transaction opened before a build claimed the template but committed
// after the build read the row would still carry a timestamp no later than
// the claim, and FinishBuild's own `data_changed_at <= claimedAt` would clear
// it — losing the very row this feature exists to keep. clock_timestamp()
// reads the moment this statement actually runs, which is always after the
// commit that made ClaimBuild's row visible to it.
func (r *GameInstances) MarkTableDataChanged(ctx context.Context, contestID uuid.UUID) error {
	if _, err := r.querier(ctx).Exec(ctx,
		`UPDATE game_templates SET data_changed_at = clock_timestamp() WHERE contest_id = $1`, contestID); err != nil {
		return fmt.Errorf("mark the contest's table data changed: %w", err)
	}
	return nil
}

// AppendTableDataRow records one more row appended to an already-'complete'
// file: its new byte length and its new row count in the one statement, so
// the two never read as having disagreed even for an instant.
//
// Both figures only ever move forward, which is what GREATEST is here for.
// A file a row was appended to never gets shorter, so a caller whose snapshot
// is older than another's must not be able to write its own smaller pair over
// the newer one — two forms adding a row to the same table at once is exactly
// that, and the last UPDATE to run is not necessarily the one that read last
// (provisioning.Games.AppendTableRow's own doc, and rowLanded for what stops
// the two from writing the same bytes twice). coalesce covers line_count's
// null, which is what a row that never completed carries.
//
// No row matched means the row is gone, or is no longer 'complete' — a
// concurrent replacement of the game discards a contest's table data
// (DiscardTableData) — and the caller is told the state it decided on is not
// there any more rather than being answered success for a row nothing counts.
func (r *GameInstances) AppendTableDataRow(ctx context.Context, id uuid.UUID, receivedBytes, lines int64) (provisioning.TableData, error) {
	data, err := scanTableData(r.querier(ctx).QueryRow(ctx, `
		UPDATE game_table_data
		SET received_bytes = GREATEST(received_bytes, $2),
		    line_count     = GREATEST(coalesce(line_count, 0), $3),
		    updated_at     = now()
		WHERE id = $1 AND status = 'complete'
		RETURNING `+tableDataColumns, id, receivedBytes, lines))
	if errors.Is(err, pgx.ErrNoRows) {
		return provisioning.TableData{}, provisioning.ErrTableDataChanged
	}
	if err != nil {
		return provisioning.TableData{}, fmt.Errorf("record the appended row: %w", err)
	}
	return data, nil
}

// AbortTableData marks one table-data upload 'aborted'.
func (r *GameInstances) AbortTableData(ctx context.Context, id uuid.UUID) error {
	if _, err := r.querier(ctx).Exec(ctx,
		`UPDATE game_table_data SET status = 'aborted', updated_at = now() WHERE id = $1`, id); err != nil {
		return fmt.Errorf("mark the table upload aborted: %w", err)
	}
	return nil
}

// DeleteTableDataRow tombstones one row of a 'complete' file: a single
// atomic array_append that also refuses a row already tombstoned (the WHERE
// clause's own NOT ... = ANY), so two concurrent deletes of the same row can
// never both believe they were the one that removed it. array_length is
// re-checked here too, past migration 27's own CHECK, purely to answer with
// this package's own sentinel instead of a bare constraint violation — the
// CHECK itself is what actually enforces the bound if this ever disagreed
// with provisioning.MaxTableDeletedRows.
func (r *GameInstances) DeleteTableDataRow(ctx context.Context, id uuid.UUID, row int64) error {
	tag, err := r.querier(ctx).Exec(ctx, `
		UPDATE game_table_data
		SET deleted_rows = array_append(deleted_rows, $2::bigint), updated_at = now()
		WHERE id = $1 AND status = 'complete' AND NOT ($2::bigint = ANY(deleted_rows))`, id, row)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == tableDataCheckViolation {
			return provisioning.ErrTooManyDeletedRows
		}
		return fmt.Errorf("delete row %d: %w", row, err)
	}
	if tag.RowsAffected() == 0 {
		// Either the row does not exist (the caller already checked that
		// against Lines before calling this), or — the case this statement's
		// own WHERE exists to catch — it was already tombstoned, by this
		// call or a concurrent one that committed first.
		return provisioning.ErrTableRowAlreadyDeleted
	}
	return nil
}

// DiscardTableData retires every table-data row of one contest that anything
// still needs — 'receiving' and 'complete' alike — and returns their ids so
// the caller can remove their bytes from the volume once its transaction has
// committed.
//
// 'aborted' rather than DELETE, the same convention MarkDropped keeps for an
// instance and AbortTableData for one upload: the row is history of a file
// that once existed, and TableDataInUse already reads 'aborted' as "nobody
// needs these bytes". One statement for the whole contest, because this runs
// inside the transaction that replaces the game (provisioning.Games.
// replaceGame) and a row-at-a-time loop there would be one round trip per
// table for no gain.
func (r *GameInstances) DiscardTableData(ctx context.Context, contestID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := r.querier(ctx).Query(ctx, `
		UPDATE game_table_data
		SET status = 'aborted', updated_at = now()
		WHERE contest_id = $1 AND status IN ('receiving', 'complete')
		RETURNING id`, contestID)
	if err != nil {
		return nil, fmt.Errorf("discard the contest's table data: %w", err)
	}
	defer rows.Close()

	var ids []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("scan a discarded table data row: %w", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("discard the contest's table data: %w", err)
	}
	return ids, nil
}

// AbandonedTableData lists up to limit table-data uploads still 'receiving'
// whose updated_at is older than cutoff, oldest first — AbandonedUploads'
// own shape.
func (r *GameInstances) AbandonedTableData(ctx context.Context, cutoff time.Time, limit int) ([]provisioning.TableData, error) {
	rows, err := r.querier(ctx).Query(ctx,
		`SELECT `+tableDataColumns+` FROM game_table_data
		 WHERE status = 'receiving' AND updated_at < $1
		 ORDER BY updated_at
		 LIMIT $2`, cutoff, limit)
	if err != nil {
		return nil, fmt.Errorf("list abandoned table uploads: %w", err)
	}
	defer rows.Close()

	var out []provisioning.TableData
	for rows.Next() {
		d, err := scanTableData(rows)
		if err != nil {
			return nil, fmt.Errorf("scan an abandoned table upload: %w", err)
		}
		out = append(out, d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list abandoned table uploads: %w", err)
	}
	return out, nil
}

// TableDataInUse reports whether anything still needs id's bytes on the
// volume: an upload still receiving chunks, or the one 'complete' file a
// table currently has — UploadInUse's own shape, at the finer grain of one
// table-data row rather than a whole game.
func (r *GameInstances) TableDataInUse(ctx context.Context, id uuid.UUID) (bool, error) {
	var inUse bool
	if err := r.querier(ctx).QueryRow(ctx, `
		SELECT EXISTS(
			SELECT 1 FROM game_table_data
			WHERE id = $1 AND status IN ('receiving', 'complete')
		)`, id).Scan(&inUse); err != nil {
		return false, fmt.Errorf("check whether table upload %s is still in use: %w", id, err)
	}
	return inUse, nil
}
