// Command auditcontract writes audit.Actions() to a file, as apicontract does
// for error codes. The frontend's dictionary test reads it directly, so an
// action not regenerated here fails `go test` and an untranslated one fails
// `npm test`; no hand-kept list remains.
//
// It is generated, committed and checked by a test:
//
//	make audit-contract
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/devrdn/db-contest/backend/internal/audit"
)

// contractFile is relative to the repository root, beside error-codes.json.
const contractFile = "docs/api/audit-actions.json"

// contractPath resolves contractFile by walking up to go.mod, since `go run`
// and `go test` start in different directories.
func contractPath() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("locate the working directory: %w", err)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return filepath.Join(filepath.Dir(dir), contractFile), nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above the working directory")
		}
		dir = parent
	}
}

// document is an object rather than a bare array, so it can gain fields.
type document struct {
	About string `json:"about"`
	// Actions is exactly audit.Actions(), unsorted and unfiltered.
	Actions []string `json:"actions"`
}

func contract() ([]byte, error) {
	out, err := json.MarshalIndent(document{
		About: "Action codes the audit trail can be filtered or shown by, in the audit " +
			"parameter and in trail rows. Generated by cmd/auditcontract from audit.Actions(); " +
			"run `make audit-contract` after adding or removing one. Each code needs a " +
			"translation in lib/i18n/dictionaries/*.ts, in every locale — dictionary.test.ts " +
			"checks that against this file, not against a copy of it.",
		Actions: audit.Actions(),
	}, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode the contract: %w", err)
	}
	return append(out, '\n'), nil
}

func main() {
	out, err := contract()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	path, err := contractPath()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	// Narrow modes: git records only the executable bit anyway.
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		fmt.Fprintf(os.Stderr, "create %s: %v\n", filepath.Dir(path), err)
		os.Exit(1)
	}
	if err := os.WriteFile(path, out, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", path)
}
