// Command auditcontract writes the audit trail's action vocabulary to a file.
//
// The interface has to translate every action code the trail can be filtered
// or displayed by, in every language it speaks. Before this existed, the
// interface's own list of actions was typed
// by hand from reading audit.go, and nothing tied the two together: an action
// added to audit.Actions() and never copied into that list still passed both
// the Go guard (audit_test.go, checked against the very same source) and the
// frontend's own translation-coverage test (checked against that same
// hand-typed list) — the vocabulary could drift on the interface side alone,
// which is the same failure this project already closed once for error codes.
//
// This publishes audit.Actions() as data, the way cmd/apicontract publishes
// httpx.Catalog(). The frontend's dictionary test reads the committed file
// directly instead of a copy of it, so an action this repository declares but
// never regenerates the contract for fails `go test ./...` here, and an
// action the contract carries with no translation fails `npm test` there —
// there is no longer a third, hand-kept list to fall behind either side.
//
// It is generated, committed and checked by a test:
//
//	make audit-contract
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/devrdn/db-contest/backend/internal/audit"
)

// contractFile is where the published contract lives, relative to the
// repository root.
//
// Under docs/api/, beside error-codes.json, for the same reason that one is:
// it belongs to neither the backend nor the interface, and is what either
// side would publish or consume first if they ever lived in separate
// repositories.
const contractFile = "docs/api/audit-actions.json"

// contractPath resolves contractFile against the repository root.
//
// Found by walking up to the directory holding go.mod rather than trusting the
// working directory: `go run ./cmd/auditcontract` starts in the module root and
// `go test` starts in the package's own directory, and a relative path cannot
// be right for both.
func contractPath() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("locate the working directory: %w", err)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return filepath.Join(filepath.Dir(dir), contractFile), nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above the working directory")
		}
		dir = parent
	}
}

// document is the published shape. A wrapper object rather than a bare array
// so the file can gain a field later without every consumer breaking.
type document struct {
	// About says what the file is, to whoever opens it without context.
	About string `json:"about"`
	// Actions is exactly what audit.Actions() returns — no ordering or
	// filtering of its own, so a diff of this file is a diff of the
	// vocabulary and nothing else.
	Actions []string `json:"actions"`
}

func contract() ([]byte, error) {
	out, err := json.MarshalIndent(document{
		About: "Action codes the audit trail can be filtered or shown by, in the audit " +
			"parameter and in trail rows. Generated by cmd/auditcontract from audit.Actions(); " +
			"run `make audit-contract` after adding or removing one. Each code needs a " +
			"translation in lib/i18n/dictionaries/*.ts, in every locale — dictionary.test.ts " +
			"checks that against this file, not against a copy of it.",
		Actions: audit.Actions(),
	}, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode the contract: %w", err)
	}
	return append(out, '\n'), nil
}

func main() {
	out, err := contract()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	path, err := contractPath()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	// Narrow modes on purpose: git records neither directory permissions nor
	// anything but the executable bit, so what is committed is unaffected and
	// there is nothing to gain by asking for more on the machine that
	// generates the file.
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		fmt.Fprintf(os.Stderr, "create %s: %v\n", filepath.Dir(path), err)
		os.Exit(1)
	}
	if err := os.WriteFile(path, out, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", path)
}
